### ISSUE TITLE
`TypeError: this._meta.byKey is not a function` error with webcomponentsjs 1.0.5

### ISSUE THREAD

**Issue by fabysdev** [PolymerElements/iron-icon#109]
### Description

`TypeError: this._meta.byKey is not a function` error in firefox and edge but not in chrome (not tested in safari, ie) when using webcomponentsjs 1.0.5, works with webcomponentsjs 1.0.4.

#### Live Demo
http://jsbin.com/wuceranate/1/edit

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [x] Edge

### Versions
- Polymer: v2.0.2
- webcomponentsjs: v1.0.5
- iron-icon: v2.0.1

**Comment by ronnyroeller** [comment]
Same issue here. Downgrading webcomponentsjs prevents indeed the issue.
@fabysdev Thanks for providing the workaround!

**Comment by abdonrd** [comment]
Same issue here!

**Comment by benjaminogles** [comment]
In the iron-icon declared properties, changing the default value of _meta to a function that returns the iron-meta instance fixed at least this issue for me.
See https://www.polymer-project.org/2.0/docs/devguide/properties#configure-values

**Comment by benjaminogles** [comment]
Not seeing the issue with webcomponents 1.0.6 in firefox

**Comment by ronnyroeller** [comment]
Good one. Upgrade to webcomponents 1.0.6 seems to solve the issue.

**Comment by notwaldorf** [comment]
This should be fixed with the new web components release, closing.
